# -*- coding: utf-8 -*-
"""educacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bglsABiw9Dr_pvtKhcnoGaJCxMgKNMnP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_csv("government-spending-on-education-by-level-per-student.csv")
df1

df2 = pd.read_csv("share-of-children-who-have-completed-school-by-education-level.csv")
df2

df1 = df1[df1["Entity"]== "Chile" ]
df1

df2 = df2[df2["Entity"]== "Chile" ]
df2

df1_nms = df1[["Year", "Upper secondary"]]
df1_nms

df2_nms = df2[["Year", "Upper secondary"]]
df2_nms

datos = pd.merge(df1_nms, df2_nms, on="Year")
datos

datos = datos.rename(columns={"Year" : "Año", "Upper secondary_x" : "Inversion", "Upper secondary_y" : "Termino"})
datos

datos.to_csv("datos.csv", index=False)

disp = sns.scatterplot(x=datos["Inversion"], y=datos["Termino"])

x = pd.DataFrame(datos, columns=["Inversion"])
y = datos["Termino"]

from sklearn.linear_model import LinearRegression

LR = LinearRegression()

LR.fit(x_cleaned, y_cleaned)

LR.score(x_cleaned, y_cleaned)

not_nan_mask = x['Inversion'].notna()
x_cleaned = x[not_nan_mask]
y_cleaned = y[not_nan_mask]

LR.fit(x_cleaned, y_cleaned)
b1=LR.coef_
print("Pendiente de la recta \n m = ", b1)

b0=LR.intercept_
print("Interseccion con el eje y \n b = ", b0)

from sklearn.metrics import r2_score

r2 = LR.score(x_cleaned, y_cleaned)
print("R^2 score = ", r2)

temp_input = 15000  # Example value, you can change this
prediccion=b0+b1[0]*temp_input

inv_max=datos.Inversion.max()
inv_max

datos.Termino.max()

inv_min=datos.Inversion.min()
inv_min

datos.Termino.min()

numero=1073736

total_min=inv_min*numero
total_min

total_max=inv_max*numero
total_max

presupuesto = 40000000000
prep_alumno= presupuesto/numero
prep_alumno

LR.fit(x_cleaned, y_cleaned)
b1 = LR.coef_

alumno1 = presupuesto * 0.40
infraestructura1= presupuesto * 0.50
docentes1 = presupuesto * 0.10

esc1=b0+prep_alumno*b1[0]+infraestructura1/1000000000*0.15+docentes1/1000000000*0.12
esc1

alumno2=prep_alumno*0.0
infraestructura2 = presupuesto *1.0
docentes2=presupuesto*0.0

esc2=alumno2*b1+infraestructura2/100000000*0.15+docentes2/100000000*0.12
esc2

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Educacion1.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# # Insertamos título
# st.write(''' # ODS 4: Educación de calidad ''')
# # Insertamos texto con formato
# st.markdown("""
# Optimización de Recursos para el Fortalecimiento Educativo.
# """)
# # Insertamos una imagen
# st.image("Goal-04.png", caption="""Impacto de diversos factores sobre la tasa de
# graduación.""")
# # Usaremos un deslizador
# st.sidebar.header("Presupuesto")
# # Definimos los parámetros de nuestro deslizador:
# # Límite inferior: 33000000000
# # Límite superior: 35000000000
# # Valor inicial: 40000000000
# presupuesto = st.sidebar.slider("Presupuesto", 6000, 2500, 1000)
# datos = pd.read_csv('datos.csv' , encoding= 'latin-1')
# # Seleccionamos las variables
# X = pd.DataFrame(datos, columns=['Inversion'])
# y = datos['Termino']
# # Creamos y entrenamos el modelo
# from sklearn.linear_model import LinearRegression
# LR = LinearRegression()
# LR.fit(X,y)
# # Extraemos los coeficientes de la regresión
# b1 = LR.coef_
# b0 = LR.intercept_
# 
# impacto = b0 + presupuesto*b1[0]
# st.metric("Impacto Proyectado ODS 4", f" +{float(impacto):.3f}%")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Educacion.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# # Insertamos título
# st.write(''' # ODS 4: Educación de calidad ''')
# # Insertamos texto con formato
# st.markdown("""
# Optimización de Recursos para el Fortalecimiento Educativo.
# """)
# # Insertamos una imagen
# st.image("Goal-04.png", caption="""Impacto de diversos factores sobre la tasa de
# graduación.""")
# # Usaremos un deslizador
# st.sidebar.header("Presupuesto")
# # Definimos los parámetros de nuestro deslizador:
# # Límite inferior: 33000000000
# # Límite superior: 35000000000
# # Valor inicial: 40000000000
# presupuesto = st.sidebar.slider("Presupuesto", 10000000000, 45000000000,
# 30000000000)
# st.sidebar.header("Porcentaje de Becas")
# porcentaje_becas = st.sidebar.slider("Porcentaje de Becas", 0.0, 1.0, 0.2)
# st.sidebar.header("Porcentaje de Infraestructura")
# porcentaje_infra = st.sidebar.slider("Porcentaje de Infraestructura", 0.0, 1.0,
# 0.5)
# st.sidebar.header("Porcentaje de Docentes")
# porcentaje_docentes = st.sidebar.slider("Porcentaje de Docentes", 0.0, 1.0, 0.15)
# # Seleccionamos las variables
# X = pd.DataFrame(datos, columns=['Inversión'])
# y = datos['Término']
# # Creamos y entrenamos el modelo
# from sklearn.linear_model import LinearRegression
# LR = LinearRegression()
# LR.fit(X,y)
# # Extraemos los coeficientes de la regresión
# b1 = LR.coef_
# b0 = LR.intercept_
# # Especificamos datos por población
# numero = 1073736
# prep_alumno = presupuesto/numero
# # Calculamos el presupuesto asignado a cada rubro
# presupuesto_becas = presupuesto * porcentaje_becas
# presupuesto_infra = presupuesto * porcentaje_infra
# presupuesto_docentes = presupuesto * porcentaje_docentes
# # Presentamos loa resultados
# total_gastado = presupuesto*(porcentaje_becas + porcentaje_infra +
# porcentaje_docentes)
# # Validar restricciones
# import warnings
# if total_gastado != presupuesto:
#     st.error("El total gastado debe ser exactamente igual al presupuesto.")
# elif presupuesto_becas < presupuesto*.40:
#     st.warning("El presupuesto de becas no cumple con el mínimo del 20%.",
# UserWarning)
# elif presupuesto_infra > presupuesto*.45:
#     st.warning("El presupuesto de infraestructura excede el tope del 50%.",
# UserWarning)
# elif presupuesto_docentes < presupuesto*.35:
#     st.warning("La capacitación docente está por debajo del 15% obligatorio.",
# UserWarning)
# else:
#     st.success("Combinación de presupuesto válida.")
# st.subheader('Impacto alcanzado')
# impacto = b0 + prep_alumno*b1[0] + presupuesto_infra/100000000*0.15 + presupuesto_docentes/100000000*.14
# st.metric("Impacto Proyectado ODS 4", f" +{float(impacto):.3f}%")
# # Presentamos el tipo de filosofía
# if porcentaje_becas >= 0.40:
#     filosofia = "Bienestar Primero (Equidad y Movilidad Social)"
# elif porcentaje_infra >= 0.45:
#     filosofia = "Rendimiento Estructural (Desarrollo Sostenible)"
# elif porcentaje_docentes >= 0.35:
#     filosofia = "Efecto Multiplicador (Excelencia Académica)"
# else:
#     filosofia = "Gobernanza Equilibrada (Modelo Balanceado)"
# st.subheader("Clasificación Estratégica del Modelo")
# st.info(f"Su propuesta: {filosofia}")