# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BE0jdQiq3saZA6WSqEw2zwLk8N8TCIYh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
n = 1000
VAR_2 = np.random.uniform(200, 1050, n)
VAR_3 = np.random.choice([300, 350, 400, 450], n)
VAR_5 = np.random.uniform(4, 12, n)

ruido = np.random.normal(0, 2.5, n)
VAR_4 = (0.085 * VAR_2) + 10 + ruido

df = pd.DataFrame({
    'VAR_1': [f'PV_{i:04d}' for i in range(n)],
    'VAR_2': VAR_2,
    'VAR_3': VAR_3,
    'VAR_4': VAR_4,
    'VAR_5': VAR_5
})

n_nulos = np.random.randint(10, 21)
for _ in range(n_nulos):
    fila = np.random.randint(0, n)
    col = np.random.choice(['VAR_2', 'VAR_4'])
    df.loc[fila, col] = np.nan

df.to_csv('energia_ODS7.csv', index=False)

df = pd.read_csv('energia_ODS7.csv')

print("Primeros registros del Dataset")
print(df.head())

print("\n estructura de datos")
df.info()

print("Cantidad de datos faltantes por columna")
print(df.isnull().sum())

df = df.dropna()
df = df.reset_index(drop=True)

print("\nDatos faltantes")
print(df.isnull().sum())
print(f"\ndataset: {df.shape}")

plt.figure(figsize=(10, 6))
plt.scatter(df['VAR_2'], df['VAR_4'], alpha=0.6, edgecolor='k')
plt.title('Relación: Radiación Solar vs Energía Generada')
plt.xlabel('Intensidad de Radiación (VAR_2)')
plt.ylabel('Energía de Salida (VAR_4)')
plt.grid(True, linestyle='--')
plt.show()

X = df[['VAR_2']]
y = df['VAR_4']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=5)

print(f"Datos de entrenamiento: {X_train.shape}")
print(f"Datos de prueba: {X_test.shape}")

from sklearn.linear_model import LinearRegression

LR = LinearRegression()
LR.fit(X_train, y_train)

print(f"Score en entrenamiento: {LR.score(X_train, y_train):.4f}")

b1 = LR.coef_
b0 = LR.intercept_

print(f"Pendiente (m): {b1[0]:.4f}")
print(f"Intersección (b): {b0:.4f}")

from sklearn.metrics import r2_score

r2 = LR.score(X_test, y_test)
print(f"R^2 score: {r2:.4f}")

pred = LR.predict(X_test)

plt.scatter(X, y, label='Datos reales', alpha=0.5)
plt.plot(X_test, pred, color='red', linewidth=2, label='Línea de Regresión')
plt.title('Modelo de Predicción de Energía asequible, segura, sostenible y moderna para todos.')
plt.xlabel('Intensidad de Radiación Solar (VAR_2)')
plt.ylabel('Energía de Salida (VAR_4)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.3)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app_fotovoltaica.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# 
# st.title("ODS 7: Energía asequible, segura, sostenible y moderna para todos.")
# st.markdown("Predicción de eficiencia basada en la radiación solar.")
# 
# st.sidebar.header("Parámetros Solares")
# radiacion_input = st.sidebar.slider("Intensidad de Radiación (VAR_2)",
#                                     min_value=200.0, max_value=1050.0, value=600.0)
# 
# df = pd.read_csv('energia_ODS7.csv')
# 
# df = df.dropna()
# df = df.reset_index(drop=True)
# 
# X = df[['VAR_2']]
# y = df['VAR_4']
# 
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)
# LR = LinearRegression()
# LR.fit(X_train, y_train)
# 
# prediccion = LR.predict([[radiacion_input]])[0]
# 
# st.subheader("Resultados")
# st.metric(label="Energía Estimada (VAR_4)", value=f"{prediccion:.2f} Watts")
# 
# if prediccion > 60:
#     st.success("Alta producción esperada")
# elif prediccion > 30:
#     st.info("Producción moderada")
# else:
#     st.warning("Baja radiación / Producción baja")
# 
# st.image("ods7.jpg",
#          caption="ODS 7: Energía Asequible y No Contaminante",
#          use_column_width=True)